dubbo:
    cloud:
        subscribed-services: ${provider.application.name}
    consumer:
        check: false
        lazy: true
    protocols:
        dubbo:
            name: dubbo
            port: 12801
    registry:
        address: spring-cloud://localhost
    scan:
        base-packages: com.winsion.net.taskservice.*

management:
    endpoints:
        web:
            exposure:
                include: dubborestmetadata
provider:
    application:
        name: task-cloud-core-userservice-provider


spring:
    datasource:
        druid:
            async-close-connection-enable: true
            filter:
                stat:
                    db-type: h2
                    log-slow-sql: true
                    slow-sql-millis: 2000
            initial-size: 2
            max-active: 30
            max-pool-prepared-statement-per-connection-size: 5
            max-wait: 1234
            min-evictable-idle-time-millis: 30001
            min-idle: 2
            pool-prepared-statements: true
            test-on-borrow: true
            test-on-return: true
            test-while-idle: true
            time-between-eviction-runs-millis: 10000
            validation-query: select 1
            validation-query-timeout: 1
        password: 123456
        url: jdbc:mysql://172.16.80.30:3306/railway_task?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
    jpa:
        show-sql: true

#Setting the logging levels for the service
logging:
    level:
        com.netflix: WARN
        org.springframework.web: WARN
        com.thoughtmechanix: DEBUG